const lessonTitle = "木瓜树";

const lessonData = [
    // ===== 第1段 =====
    ["我", "wǒ", "I", "saya"],
    ["小时候", "xiǎo shí hou", "when I was young", "semasa kecil"],
    ["，", "", "", ""],
    ["家里", "jiā lǐ", "at home", "di rumah"],
    ["没种", "méi zhòng", "did not plant", "tidak menanam"],
    ["什么", "shén me", "any", "apa-apa"],
    ["水果", "shuǐ guǒ", "fruit", "buah"],
    ["，", "", "", ""],
    ["要吃", "yào chī", "to eat", "untuk makan"],
    ["水果", "shuǐ guǒ", "fruit", "buah"],
    ["，", "", "", ""],
    ["都", "dōu", "all", "semua"],
    ["得到", "dé dào", "had to go to", "perlu pergi ke"],
    ["镇上", "zhèn shàng", "town", "pekan"],
    ["去", "qù", "go", "pergi"],
    ["买", "mǎi", "buy", "beli"],
    ["。", "", "", ""],
    ["父母亲", "fù mǔ qīn", "My parents", "Ibu bapa"],
    ["工作忙", "gōng zuò máng", "busy with work", "sibuk bekerja"],
    ["，", "", "", ""],
    ["很少", "hěn shǎo", "seldom", "jarang"],
    ["到镇上", "dào zhèn shàng", "go to town", "pergi ke pekan"],
    ["去", "qù", "", ""],
    ["，", "", "", ""],
    ["所以", "suǒ yǐ", "so", "maka"],
    ["我们", "wǒ men", "we", "kami"],
    ["也", "yě", "also", "juga"],
    ["很难得", "hěn nán dé", "rarely", "sukar"],
    ["吃一次", "chī yī cì", "eat once", "makan sekali"],
    ["水果", "shuǐ guǒ", "fruit", "buah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["有一天", "yǒu yī tiān", "One day", "Pada suatu hari"],
    ["，", "", "", ""],
    ["父亲", "fù qīn", "Father", "Ayah"],
    ["到镇上", "dào zhèn shàng", "went to town", "pergi ke pekan"],
    ["去", "qù", "", ""],
    ["，", "", "", ""],
    ["买了", "mǎi le", "bought", "membeli"],
    ["一个", "yī gè", "a", "sebuah"],
    ["大木瓜", "dà mù guā", "big papaya", "betik besar"],
    ["回来", "huí lái", "back", "pulang"],
    ["。", "", "", ""],
    ["那木瓜", "nà mù guā", "That papaya", "Betik itu"],
    ["的", "de", "", ""],
    ["皮", "pí", "skin", "kulit"],
    ["，", "", "", ""],
    ["虽是", "suī shì", "although", "walaupun"],
    ["变黄了", "biàn huáng le", "turned yellow", "telah kuning"],
    ["，", "", "", ""],
    ["却", "què", "yet", "tetapi"],
    ["还有点儿硬", "hái yǒu diǎn r yìng", "still a bit hard", "masih agak keras"],
    ["，", "", "", ""],
    ["母亲", "mǔ qīn", "Mother", "Ibu"],
    ["把它", "bǎ tā", "put it", "meletakkannya"],
    ["放在", "fàng zài", "in", "di dalam"],
    ["米缸里", "mǐ gāng lǐ", "rice jar", "tempayan beras"],
    ["，", "", "", ""],
    ["说是", "shuō shì", "saying that", "berkata bahawa"],
    ["那样", "nà yàng", "that way", "dengan begitu"],
    ["熟得快", "shú de kuài", "ripen faster", "cepat masak"],
    ["。", "", "", ""],
    ["第二天", "dì èr tiān", "The next day", "Keesokan harinya"],
    ["吃过", "chī guò", "after having", "selepas makan"],
    ["中饭", "zhōng fàn", "lunch", "makan tengah hari"],
    ["，", "", "", ""],
    ["母亲", "mǔ qīn", "Mother", "Ibu"],
    ["把木瓜", "bǎ mù guā", "took the papaya", "mengambil betik"],
    ["拿出来", "ná chū lái", "out", "keluar"],
    ["，", "", "", ""],
    ["果然", "guǒ rán", "indeed", "memang"],
    ["软了", "ruǎn le", "softened", "lembut"],
    ["许多", "xǔ duō", "much", "banyak"],
    ["。", "", "", ""],
    ["母亲", "mǔ qīn", "Mother", "Ibu"],
    ["把它", "bǎ tā", "it", "ia"],
    ["洗净", "xǐ jìng", "washed", "membasuh"],
    ["剖开", "pōu kāi", "cut open", "membelah"],
    ["，", "", "", ""],
    ["只见", "zhǐ jiàn", "saw", "nampak"],
    ["里面", "lǐ miàn", "inside", "di dalam"],
    ["密密麻麻的", "mì mì má má de", "densely packed", "padat"],
    ["，", "", "", ""],
    ["藏了", "cáng le", "hidden", "tersembunyi"],
    ["许多", "xǔ duō", "many", "banyak"],
    ["黑色的", "hēi sè de", "black", "hitam"],
    ["木瓜籽", "mù guā zǐ", "papaya seeds", "biji betik"],
    ["。", "", "", ""],
    ["母亲", "mǔ qīn", "Mother", "Ibu"],
    ["把木瓜籽", "bǎ mù guā zǐ", "scraped the seeds", "mengikis biji"],
    ["刮下来", "guā xià lái", "", ""],
    ["，", "", "", ""],
    ["放在", "fàng zài", "placed in", "meletakkan di"],
    ["一个", "yī gè", "a", "sebuah"],
    ["铝盘里", "lǚ pán lǐ", "aluminum tray", "dulang aluminium"],
    ["。", "", "", ""],
    ["我问母亲", "wǒ wèn mǔ qīn", "I asked Mother", "Saya bertanya ibu"],
    ["为什么", "wèi shén me", "why", "kenapa"],
    ["不扔掉", "bù rēng diào", "not throw away", "tidak buang"],
    ["，", "", "", ""],
    ["她说", "tā shuō", "she said", "dia berkata"],
    ["要留下来", "yào liú xià lái", "to keep them", "hendak simpan"],
    ["晒干了", "shài gàn le", "dry them", "jemur kering"],
    ["好撒种", "hǎo sā zhǒng", "to sow", "untuk ditabur benih"],
    ["，", "", "", ""],
    ["要是", "yào shì", "if", "jika"],
    ["种成了", "zhòng chéng le", "successfully planted", "berjaya ditanam"],
    ["，", "", "", ""],
    ["以后", "yǐ hòu", "later", "selepas ini"],
    ["我们", "wǒ men", "we", "kami"],
    ["就", "jiù", "then", "maka"],
    ["常有", "cháng yǒu", "often have", "sering ada"],
    ["水果吃了", "shuǐ guǒ chī le", "fruit to eat", "buah untuk dimakan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["过了不久", "guò le bù jiǔ", "Not long after", "Tidak lama kemudian"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["发现", "fā xiàn", "discovered", "menemui"],
    ["，", "", "", ""],
    ["在我家", "zài wǒ jiā", "at my home", "di rumah saya"],
    ["屋后的", "wū hòu de", "behind the house", "belakang rumah"],
    ["菜园里", "cài yuán lǐ", "vegetable garden", "kebun sayur"],
    ["冒出", "mào chū", "sprouted", "tumbuh"],
    ["十多棵", "shí duō kē", "more than ten", "lebih sepuluh batang"],
    ["不太像", "bù tài xiàng", "not quite like", "tidak begitu seperti"],
    ["蔬菜的", "shū cài de", "vegetables", "sayur-sayuran"],
    ["绿色植物", "lǜ sè zhí wù", "green plants", "tumbuhan hijau"],
    ["。", "", "", ""],
    ["我问母亲", "wǒ wèn mǔ qīn", "I asked Mother", "Saya bertanya ibu"],
    ["，", "", "", ""],
    ["那是什么菜", "nà shì shén me cài", "what vegetable was that", "sayur apa itu"],
    ["，", "", "", ""],
    ["母亲笑着说", "mǔ qīn xiào zhe shuō", "Mother smiled and said", "Ibu tersenyum dan berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["就是木瓜树呀", "jiù shì mù guā shù ya", "They are papaya trees", "Itulah pokok betik"],
    ["！”", "", "", ""],
    ["我和妹妹", "wǒ hé mèi mei", "My sister and I", "Saya dan adik"],
    ["高兴极了", "gāo xìng jí le", "very happy", "sangat gembira"],
    ["，", "", "", ""],
    ["赶紧", "gǎn jǐn", "hurriedly", "cepat-cepat"],
    ["跑到菜园去", "pǎo dào cài yuán qù", "ran to the garden", "berlari ke kebun"],
    ["，", "", "", ""],
    ["十分珍惜地", "shí fēn zhēn xī de", "cherishingly", "dengan penuh kasih"],
    ["抚摸", "fǔ mō", "stroked", "mengusap"],
    ["每一棵", "měi yī kē", "every", "setiap batang"],
    ["木瓜树", "mù guā shù", "papaya tree", "pokok betik"],
    ["的", "de", "", ""],
    ["叶子", "yè zi", "leaves", "daun"],
    ["，", "", "", ""],
    ["仿佛", "fǎng fú", "as if", "seolah-olah"],
    ["是在", "shì zài", "were", "sedang"],
    ["勉励", "miǎn lì", "encouraging", "memberi semangat"],
    ["它们", "tā men", "them", "mereka"],
    ["：", "", "", ""],
    ["别辜负了", "bié gū fù le", "don't disappoint", "jangan kecewakan"],
    ["我们对你的希望呀", "wǒ men duì nǐ de xī wàng ya", "our hopes for you", "harapan kami terhadap awak"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["母亲", "mǔ qīn", "Mother", "Ibu"],
    ["把那些", "bǎ nà xiē", "transplanted those", "memindahkan"],
    ["小小的", "xiǎo xiǎo de", "small", "kecil"],
    ["木瓜树", "mù guā shù", "papaya trees", "pokok betik"],
    ["，", "", "", ""],
    ["分别", "fēn bié", "separately", "secara berasingan"],
    ["移植在", "yí zhí zài", "to", "ke"],
    ["菜园的", "cài yuán de", "garden's", "kebun punya"],
    ["四周", "sì zhōu", "around", "sekeliling"],
    ["，", "", "", ""],
    ["并且", "bìng qiě", "and", "dan"],
    ["殷勤地", "yīn qín de", "diligently", "dengan tekun"],
    ["浇水", "jiāo shuǐ", "watered", "menyiram"],
    ["和", "hé", "and", "dan"],
    ["施肥", "shī féi", "fertilized", "membaja"],
    ["。", "", "", ""],
    ["它们", "tā men", "They", "Mereka"],
    ["一天天地", "yī tiān tiān de", "day by day", "hari demi hari"],
    ["长大", "zhǎng dà", "grew", "membesar"],
    ["，", "", "", ""],
    ["没过多久", "méi guò duō jiǔ", "not long after", "tidak lama kemudian"],
    ["，", "", "", ""],
    ["就", "jiù", "already", "sudah"],
    ["都比", "dōu bǐ", "were taller than", "lebih tinggi daripada"],
    ["我和妹妹", "wǒ hé mèi mei", "my sister and I", "saya dan adik"],
    ["高了", "gāo le", "taller", "tinggi"],
    ["。", "", "", ""],
    ["等到", "děng dào", "When", "Apabila"],
    ["它们", "tā men", "they", "mereka"],
    ["开花结果时", "kāi huā jié guǒ shí", "bloomed and bore fruit", "berbunga dan berbuah"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kami"],
    ["就", "jiù", "had to", "perlu"],
    ["得", "děi", "", ""],
    ["仰起头来", "yǎng qǐ tóu lái", "look up", "mendongak"],
    ["，", "", "", ""],
    ["才能", "cái néng", "to be able to", "baru boleh"],
    ["看到", "kàn dào", "see", "melihat"],
    ["它的", "tā de", "their", "mereka punya"],
    ["顶端", "dǐng duān", "top", "puncak"],
    ["。", "", "", ""],
    ["起先", "qǐ xiān", "At first", "Pada mulanya"],
    ["，", "", "", ""],
    ["我和妹妹", "wǒ hé mèi mei", "my sister and I", "saya dan adik"],
    ["每天都", "měi tiān dōu", "every day", "setiap hari"],
    ["兴奋地", "xīng fèn de", "excitedly", "dengan teruja"],
    ["跑到", "pǎo dào", "ran to", "berlari ke"],
    ["木瓜树下", "mù guā shù xià", "under the papaya trees", "di bawah pokok betik"],
    ["去巡视", "qù xún shì", "to inspect", "untuk memeriksa"],
    ["，", "", "", ""],
    ["看看到底", "kàn kan dào dǐ", "to see how many", "melihat berapa banyak"],
    ["结了几个", "jié le jǐ gè", "fruits there were", "buah yang ada"],
    ["木瓜", "mù guā", "papayas", "betik"],
    ["。", "", "", ""],
    ["后来", "hòu lái", "Later", "Kemudian"],
    ["木瓜", "mù guā", "papayas", "betik"],
    ["越结越多", "yuè jié yuè duō", "more and more", "semakin banyak"],
    ["，", "", "", ""],
    ["我和妹妹", "wǒ hé mèi mei", "my sister and I", "saya dan adik"],
    ["仰着头", "yǎng zhe tóu", "looking up", "mendongak"],
    ["，", "", "", ""],
    ["数到", "shǔ dào", "counted until", "mengira sehingga"],
    ["脖子发酸", "bó zi fā suān", "necks sore", "leher sakit"],
    ["，", "", "", ""],
    ["也", "yě", "still", "masih"],
    ["还是", "hái shì", "", ""],
    ["数不完", "shǔ bù wán", "couldn't finish counting", "tidak habis dikira"],
    ["；", "", "", ""],
    ["而且因为太多", "ér qiě yīn wèi tài duō", "and because there were too many", "dan kerana terlalu banyak"],
    ["，", "", "", ""],
    ["老是数错", "lǎo shì shǔ cuò", "always counted wrong", "selalu tersilap kira"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kami"],
    ["就", "jiù", "then", "maka"],
    ["懒得", "lǎn de", "couldn't be bothered", "malas"],
    ["再去数了", "zài qù shǔ le", "to count anymore", "untuk mengira lagi"],
    ["。", "", "", ""],
    ["不过", "bù guò", "However", "Tetapi"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kami"],
    ["还是", "hái shì", "still", "masih"],
    ["常到", "cháng dào", "often went to", "sering pergi ke"],
    ["木瓜树下", "mù guā shù xià", "under the papaya trees", "di bawah pokok betik"],
    ["去巡视", "qù xún shì", "to inspect", "untuk memeriksa"],
    ["，", "", "", ""],
    ["看看", "kàn kan", "to see", "melihat"],
    ["哪个木瓜", "nǎ ge mù guā", "which papaya", "betik yang mana"],
    ["开始转黄了", "kāi shǐ zhuǎn huáng le", "started turning yellow", "mula menjadi kuning"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["在我们", "zài wǒ men", "In our", "Dalam"],
    ["焦急的", "jiāo jí de", "anxious", "cemas"],
    ["盼望中", "pàn wàng zhōng", "expectation", "penantian"],
    ["，", "", "", ""],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["有一个", "yǒu yī gè", "there was one", "ada sebiji"],
    ["木瓜", "mù guā", "papaya", "betik"],
    ["，", "", "", ""],
    ["出现了", "chū xiàn le", "appeared", "muncul"],
    ["金黄色的", "jīn huáng sè de", "golden-yellow", "kuning keemasan"],
    ["斑点", "bān diǎn", "spots", "bintik-bintik"],
    ["。", "", "", ""],
    ["使我们诧异的", "shǐ wǒ men chà yì de", "What surprised us", "Yang memeranjatkan kami"],
    ["是", "shì", "was", "ialah"],
    ["，", "", "", ""],
    ["那诱人的", "nà yòu rén de", "that tempting", "yang menarik"],
    ["，", "", "", ""],
    ["成熟的", "chéng shú de", "ripe", "masak"],
    ["斑点", "bān diǎn", "spots", "bintik-bintik"],
    ["，", "", "", ""],
    ["竟", "jìng", "unexpectedly", "rupanya"],
    ["像是", "xiàng shì", "like", "seperti"],
    ["一种", "yī zhǒng", "a kind of", "sejenis"],
    ["可爱的病菌", "kě ài de bìng jūn", "lovely virus", "virus yang comel"],
    ["，", "", "", ""],
    ["在许多木瓜中", "zài xǔ duō mù guā zhōng", "among many papayas", "di antara banyak betik"],
    ["散播着", "sàn bō zhe", "spreading", "menyebar"],
    ["。", "", "", ""],
    ["我们突然发现", "wǒ men tū rán fā xiàn", "We suddenly discovered", "Kami tiba-tiba mendapati"],
    ["，", "", "", ""],
    ["我们将会", "wǒ men jiāng huì", "we would have", "kami akan ada"],
    ["有一时", "yǒu yī shí", "for a while", "untuk seketika"],
    ["吃不完的", "chī bù wán de", "more than we could eat", "tidak habis dimakan"],
    ["木瓜了", "mù guā le", "papayas", "betik"],
    ["。", "", "", ""],
    ["那段日子", "nà duàn rì zi", "During that time", "Pada masa itu"],
    ["，", "", "", ""],
    ["我真是", "wǒ zhēn shì", "I truly", "Saya benar-benar"],
    ["感到", "gǎn dào", "felt", "merasa"],
    ["从未有过的", "cóng wèi yǒu guò de", "unprecedented", "yang tidak pernah ada"],
    ["满足", "mǎn zú", "satisfaction", "kepuasan"],
    ["和快乐", "hé kuài lè", "and happiness", "dan kegembiraan"],
    ["。", "", "", ""],
    ["不论什么时候", "bù lùn shén me shí hou", "No matter when", "Tidak kira bila"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["往屋后的菜园一望", "wǎng wū hòu de cài yuán yī wàng", "looked at the garden behind the house", "memandang ke kebun belakang rumah"],
    ["，", "", "", ""],
    ["总会", "zǒng huì", "would always", "akan sentiasa"],
    ["看到", "kàn dào", "see", "melihat"],
    ["结实累累", "jiē shi lěi lěi", "heavy with fruits", "berbuah lebat"],
    ["的", "de", "", ""],
    ["木瓜树", "mù guā shù", "papaya trees", "pokok betik"],
    ["。", "", "", ""],
    ["那些", "nà xiē", "Those", "Betik-betik itu"],
    ["静静垂挂着的", "jìng jìng chuí guà zhe de", "quietly hanging", "yang tergantung senyap"],
    ["木瓜", "mù guā", "papayas", "betik"],
    ["，", "", "", ""],
    ["硕大光洁", "shuò dà guāng jié", "large and glossy", "besar dan berkilat"],
    ["，", "", "", ""],
    ["黄绿错综", "huáng lǜ cuò zōng", "yellow and green interwoven", "kuning dan hijau bercampur"],
    ["，", "", "", ""],
    ["就像", "jiù xiàng", "like", "seperti"],
    ["一幅", "yī fú", "a", "sehelai"],
    ["富足而美丽的", "fù zú ér měi lì de", "rich and beautiful", "kaya dan cantik"],
    ["静物图画", "jìng wù tú huà", "still life painting", "lukisan benda mati"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["而木瓜", "ér mù guā", "And papayas", "Dan betik"],
    ["带给我们的", "dài gěi wǒ men de", "brought us", "memberi kami"],
    ["，", "", "", ""],
    ["当然不只是", "dāng rán bù zhǐ shì", "certainly not only", "tentu bukan sahaja"],
    ["这种", "zhè zhǒng", "this kind of", "jenis ini"],
    ["视觉的满足", "shì jué de mǎn zú", "visual satisfaction", "kepuasan visual"],
    ["。", "", "", ""],
    ["更重要的", "gèng zhòng yào de", "More importantly", "Yang lebih penting"],
    ["是", "shì", "is", "ialah"],
    ["，", "", "", ""],
    ["在味觉上", "zài wèi jué shàng", "in taste", "dalam rasa"],
    ["，", "", "", ""],
    ["它带给我们的", "tā dài gěi wǒ men de", "it brought us", "ia memberi kami"],
    ["是甜美", "shì tián měi", "sweetness", "kemanisan"],
    ["。", "", "", ""],
    ["几乎", "jī hū", "Almost", "Hampir"],
    ["每顿饭后", "měi dùn fàn hòu", "after every meal", "selepas setiap makan"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kami"],
    ["都能", "dōu néng", "could", "boleh"],
    ["吃到", "chī dào", "eat", "makan"],
    ["一盘盘", "yī pán pán", "plates of", "pinggan-pinggan"],
    ["金黄色的木瓜", "jīn huáng sè de mù guā", "golden papayas", "betik kuning keemasan"],
    ["。", "", "", ""],
    ["父亲说", "fù qīn shuō", "Father said", "Ayah berkata"],
    ["，", "", "", ""],
    ["木瓜", "mù guā", "papayas", "betik"],
    ["不仅有", "bù jǐn yǒu", "not only have", "bukan sahaja ada"],
    ["丰富的营养", "fēng fù de yíng yǎng", "rich nutrition", "khasiat yang kaya"],
    ["，", "", "", ""],
    ["饭后吃了", "fàn hòu chī le", "eating after meals", "dimakan selepas makan"],
    ["还能", "hái néng", "can also", "juga boleh"],
    ["帮助消化", "bāng zhù xiāo huà", "aid digestion", "membantu pencernaan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    ["还有一个现象", "hái yǒu yī gè xiàn xiàng", "There is another phenomenon", "Ada satu lagi fenomena"],
    ["是最微妙的", "shì zuì wēi miào de", "is the most subtle", "yang paling halus"],
    ["。", "", "", ""],
    ["以前", "yǐ qián", "Before", "Dahulu"],
    ["我们", "wǒ men", "we", "kami"],
    ["要", "yào", "had to", "perlu"],
    ["到镇上", "dào zhèn shàng", "go to town", "pergi ke pekan"],
    ["买木瓜吃", "mǎi mù guā chī", "buy papayas", "beli betik"],
    ["，", "", "", ""],
    ["现在", "xiàn zài", "now", "sekarang"],
    ["父亲或母亲", "fù qīn huò mǔ qīn", "Father or Mother", "Ayah atau Ibu"],
    ["到镇上", "dào zhèn shàng", "go to town", "pergi ke pekan"],
    ["，", "", "", ""],
    ["反而", "fǎn ér", "instead", "sebaliknya"],
    ["要带几个木瓜", "yào dài jǐ gè mù guā", "would bring a few papayas", "akan membawa beberapa biji betik"],
    ["，", "", "", ""],
    ["去给", "qù gěi", "to give to", "untuk memberi kepada"],
    ["住在镇上的", "zhù zài zhèn shàng de", "living in town", "yang tinggal di pekan"],
    ["外公", "wài gōng", "grandfather", "datuk"],
    ["和", "hé", "and", "dan"],
    ["外婆吃", "wài pó chī", "grandmother to eat", "nenek makan"],
    ["。", "", "", ""],
    ["我们也常", "wǒ men yě cháng", "We also often", "Kami juga sering"],
    ["把熟透了的木瓜", "bǎ shú tòu le de mù guā", "gave ripe papayas", "memberi betik yang masak"],
    ["送给邻居", "sòng gěi lín jū", "to neighbors", "kepada jiran"],
    ["。", "", "", ""],
    ["他们", "tā men", "They", "Mereka"],
    ["吃完了木瓜", "chī wán le mù guā", "after eating the papayas", "selepas makan betik"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["把种籽留下", "bǎ zhǒng zǐ liú xià", "kept the seeds", "menyimpan biji"],
    ["，", "", "", ""],
    ["在屋前屋后", "zài wū qián wū hòu", "in front and behind the house", "di depan dan belakang rumah"],
    ["撒下去", "sǎ xià qù", "sowed them", "menaburkan"],
    ["，", "", "", ""],
    ["长出", "zhǎng chū", "grew", "tumbuh"],
    ["小小的", "xiǎo xiǎo de", "small", "kecil"],
    ["木瓜树来了", "mù guā shù lái le", "papaya trees", "pokok betik"],
    ["。", "", "", ""],
    ["有时母亲", "yǒu shí mǔ qīn", "Sometimes Mother", "Kadang-kadang Ibu"],
    ["也叫我", "yě jiào wǒ", "also asked me", "juga menyuruh saya"],
    ["提两个木瓜", "tí liǎng gè mù guā", "carry two papayas", "bawa dua biji betik"],
    ["，", "", "", ""],
    ["去送给", "qù sòng gěi", "to give to", "untuk memberi kepada"],
    ["学校的老师", "xué xiào de lǎo shī", "school teachers", "guru sekolah"],
    ["。", "", "", ""],
    ["那时", "nà shí", "At that time", "Pada masa itu"],
    ["我才上", "wǒ cái shàng", "I was only in", "saya baru"],
    ["小学三年级", "xiǎo xué sān nián jí", "third grade", "tahun tiga"],
    ["，", "", "", ""],
    ["一次提两个木瓜", "yī cì tí liǎng gè mù guā", "carrying two papayas at a time", "membawa dua biji betik pada satu masa"],
    ["已经是", "yǐ jīng shì", "was already", "sudah"],
    ["相当吃力了", "xiāng dāng chī lì le", "quite strenuous", "agak berat"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    ["就是那", "jiù shì nà", "Even those", "Malahan yang"],
    ["没有成熟的", "méi yǒu chéng shú de", "unripe", "tidak masak"],
    ["木瓜", "mù guā", "papayas", "betik"],
    ["，", "", "", ""],
    ["也仍然", "yě réng rán", "also still", "juga masih"],
    ["有独特的", "yǒu dú tè de", "have unique", "mempunyai"],
    ["价值", "jià zhí", "value", "nilai"],
    ["。", "", "", ""],
    ["听说", "tīng shuō", "I heard", "Saya dengar"],
    ["青木瓜汁", "qīng mù guā zhī", "green papaya juice", "jus betik muda"],
    ["可以", "kě yǐ", "can", "boleh"],
    ["治胃病", "zhì wèi bìng", "treat stomach ailments", "merawat sakit perut"],
    ["，", "", "", ""],
    ["我们邻居", "wǒ men lín jū", "Our neighbors", "Jiran kami"],
    ["有得胃病的", "yǒu dé wèi bìng de", "who had stomach ailments", "yang ada sakit perut"],
    ["，", "", "", ""],
    ["常到", "cháng dào", "often came to", "sering datang ke"],
    ["我们菜园", "wǒ men cài yuán", "our garden", "kebun kami"],
    ["来摘木瓜", "lái zhāi mù guā", "to pick papayas", "untuk memetik betik"],
    ["，", "", "", ""],
    ["回去", "huí qù", "go home", "pulang"],
    ["捣汁喝", "dǎo zhī hē", "to make juice", "untuk membuat jus"],
    ["。", "", "", ""],
    ["我们家里", "wǒ men jiā lǐ", "In our family", "Dalam keluarga kami"],
    ["没有得胃病的人", "méi yǒu dé wèi bìng de rén", "no one had stomach ailments", "tiada orang sakit perut"],
    ["，", "", "", ""],
    ["不过", "bù guò", "however", "tetapi"],
    ["，", "", "", ""],
    ["母亲却", "mǔ qīn què", "Mother would", "Ibu pula"],
    ["拿青木瓜", "ná qīng mù guā", "use green papayas", "menggunakan betik muda"],
    ["来炖肉", "lái dùn ròu", "to stew meat", "untuk merebus daging"],
    ["和烧汤", "hé shāo tāng", "and make soup", "dan memasak sup"],
    ["，", "", "", ""],
    ["味道", "wèi dào", "the flavor", "rasa"],
    ["非常的鲜香", "fēi cháng de xiān xiāng", "very delicious", "sangat sedap"],
    ["。", "", "", ""],
    ["那时", "nà shí", "At that time", "Pada masa itu"],
    ["我最爱喝的", "wǒ zuì ài hē de", "my favorite", "yang paling saya suka minum"],
    ["一道汤", "yī dào tāng", "soup", "sup"],
    ["，", "", "", ""],
    ["是用青木瓜丝", "shì yòng qīng mù guā sī", "was made with green papaya shreds", "diperbuat daripada hirisan betik muda"],
    ["、丁香鱼", "dīng xiāng yú", "anchovies", "ikan bilis"],
    ["和豆酱同煮的", "hé dòu jiàng tóng zhǔ de", "and bean paste", "dan pes kacang soya"],
    ["，", "", "", ""],
    ["鲜美极了", "xiān měi jí le", "extremely delicious", "sangat sedap"],
    ["，", "", "", ""],
    ["一点儿味精", "yī diǎn r wèi jīng", "not even a little MSG", "sedikit pun MSG"],
    ["都不必放", "dōu bù bì fàng", "didn't need to add", "tidak perlu dimasukkan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    ["不管", "bù guǎn", "No matter", "Tidak kira"],
    ["我们", "wǒ men", "how we", "kami"],
    ["怎么", "zěn me", "how", "bagaimana"],
    ["想办法", "xiǎng bàn fǎ", "tried", "cuba"],
    ["消耗", "xiāo hào", "to consume", "untuk menghabiskan"],
    ["，", "", "", ""],
    ["木瓜", "mù guā", "papayas", "betik"],
    ["总", "zǒng", "still", "masih"],
    ["还是", "hái shì", "", ""],
    ["那么多", "nà me duō", "so many", "begitu banyak"],
    ["，", "", "", ""],
    ["仿佛", "fǎng fú", "as if", "seolah-olah"],
    ["永远吃不完", "yǒng yuǎn chī bù wán", "never ending", "tidak pernah habis"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    ["第二年夏天", "dì èr nián xià tiān", "The next summer", "Musim panas tahun berikutnya"],
    ["，", "", "", ""],
    ["那十多棵", "nà shí duō kē", "those more than ten", "lebih sepuluh batang"],
    ["木瓜树", "mù guā shù", "papaya trees", "pokok betik"],
    ["，", "", "", ""],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["在", "zài", "in", "dalam"],
    ["台风里", "tái fēng lǐ", "typhoon", "taufan"],
    ["离开我们而去了", "lí kāi wǒ men ér qù le", "left us", "meninggalkan kami"],
    ["。", "", "", ""],
    ["那次", "nà cì", "That", "Kali itu"],
    ["的台风", "de tái fēng", "typhoon", "taufan"],
    ["特别凶猛", "tè bié xiōng měng", "especially fierce", "sangat ganas"],
    ["，", "", "", ""],
    ["学校都停课了", "xué xiào dōu tíng kè le", "schools were closed", "sekolah semua ditutup"],
    ["。", "", "", ""],
    ["我和妹妹", "wǒ hé mèi mei", "My sister and I", "Saya dan adik"],
    ["静坐在窗边", "jìng zuò zài chuāng biān", "sat quietly by the window", "duduk diam di tepi tingkap"],
    ["，", "", "", ""],
    ["凝望着", "níng wàng zhe", "gazing at", "memandang"],
    ["菜园里的", "cài yuán lǐ de", "the garden's", "kebun punya"],
    ["木瓜树", "mù guā shù", "papaya trees", "pokok betik"],
    ["，", "", "", ""],
    ["菜园的竹篱笆", "cài yuán de zhú lí ba", "the garden's bamboo fence", "pagar buluh kebun"],
    ["，", "", "", ""],
    ["已经被风吹倒", "yǐ jīng bèi fēng chuī dǎo", "had already been blown down", "telah diterbangkan angin"],
    ["。", "", "", ""],
    ["风呼呼地狂啸着", "fēng hū hū de kuáng xiào zhe", "The wind howled fiercely", "Angin menderu-deru"],
    ["，", "", "", ""],
    ["暴雨一阵紧似一阵", "bào yǔ yī zhèn jǐn sì yī zhèn", "rain pouring harder and harder", "hujan lebat semakin kuat"],
    ["，", "", "", ""],
    ["天地真的都变色了", "tiān dì zhēn de dōu biàn sè le", "the sky and earth truly changed", "langit dan bumi benar-benar berubah"],
    ["。", "", "", ""],
    ["那十多棵", "nà shí duō kē", "those more than ten", "lebih sepuluh batang"],
    ["结实累累的", "jiē shi lěi lěi de", "fruit-laden", "berbuah lebat"],
    ["木瓜树", "mù guā shù", "papaya trees", "pokok betik"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["一棵棵", "yī kē kē", "one by one", "satu demi satu"],
    ["被风吹倒了", "bèi fēng chuī dǎo le", "were blown down", "diterbangkan angin"],
    ["下去", "xià qù", "", ""],
    ["，", "", "", ""],
    ["每倒下一棵", "měi dǎo xià yī kē", "every time one fell", "setiap kali sebatang tumbang"],
    ["，", "", "", ""],
    ["我和妹妹", "wǒ hé mèi mei", "my sister and I", "saya dan adik"],
    ["就心疼地", "jiù xīn téng de", "would painfully", "akan dengan sayu"],
    ["惊呼一声", "jīng hū yī shēng", "cry out", "menjerit"],
    ["。", "", "", ""],
    ["它们有的", "tā men yǒu de", "Some of them", "Sebahagian daripadanya"],
    ["是倒在竹篱上", "shì dǎo zài zhú lí shàng", "fell on the bamboo fence", "tumbang di pagar buluh"],
    ["，", "", "", ""],
    ["有的是", "yǒu de shì", "some were", "ada yang"],
    ["三四棵交错地倒在一起", "sān sì kē jiāo cuò de dǎo zài yī qǐ", "three or four intertwined together", "tiga empat batang berselang-seli rebah bersama"],
    ["。", "", "", ""],
    ["我和妹妹", "wǒ hé mèi mei", "My sister and I", "Saya dan adik"],
    ["忍不住", "rěn bù zhù", "couldn't help", "tidak tahan"],
    ["伤心地大哭起来", "shāng xīn de dà kū qǐ lái", "cried bitterly", "menangis dengan sedih"],
    ["。", "", "", ""],
    ["边哭", "biān kū", "While crying", "Sambil menangis"],
    ["我还", "wǒ hái", "I also", "saya juga"],
    ["恨恨地骂着", "hèn hèn de mà zhe", "cursed angrily", "memaki dengan marah"],
    ["，", "", "", ""],
    ["讨厌的台风", "tǎo yàn de tái fēng", "hateful typhoon", "taufan yang menjengkelkan"],
    ["！", "", "", ""],
    ["妹妹马上", "mèi mei mǎ shàng", "My sister immediately", "Adik segera"],
    ["哀哀地接着说道", "āi āi de jiē zhe shuō dào", "sadly said", "dengan sedih menyambung"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["可怜的木瓜树啊", "kě lián de mù guā shù a", "Poor papaya trees", "Pokok betik yang malang"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    ["风雨过后", "fēng yǔ guò hòu", "After the storm", "Selepas ribut"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kami"],
    ["都", "dōu", "all", "semua"],
    ["跑到菜园里", "pǎo dào cài yuán lǐ", "ran to the garden", "berlari ke kebun"],
    ["，", "", "", ""],
    ["要设法", "yào shè fǎ", "to try", "untuk cuba"],
    ["抢救", "qiǎng jiù", "rescue", "menyelamatkan"],
    ["那些木瓜树", "nà xiē mù guā shù", "those papaya trees", "pokok betik itu"],
    ["。", "", "", ""],
    ["然而", "rán ér", "However", "Namun"],
    ["，", "", "", ""],
    ["它们", "tā men", "they", "mereka"],
    ["似乎", "sì hū", "seemed", "seolah-olah"],
    ["都已受创太深", "dōu yǐ shòu chuàng tài shēn", "all too severely damaged", "semua telah teruk rosak"],
    ["，", "", "", ""],
    ["回生乏术了", "huí shēng fá shù le", "beyond revival", "tidak dapat dipulihkan"],
    ["。", "", "", ""],
    ["它们的叶子", "tā men de yè zi", "Their leaves", "Daun-daun mereka"],
    ["，", "", "", ""],
    ["全被风雨", "quán bèi fēng yǔ", "all by the wind and rain", "semuanya oleh angin dan hujan"],
    ["打得稀烂", "dǎ de xī làn", "shredded", "koyak-rabak"],
    ["。", "", "", ""],
    ["它们的身子", "tā men de shēn zi", "Their trunks", "Batang mereka"],
    ["，", "", "", ""],
    ["有的拦腰折断", "yǒu de lán yāo zhé duàn", "some broken in the middle", "ada yang patah di tengah"],
    ["，", "", "", ""],
    ["有的连根拔起", "yǒu de lián gēn bá qǐ", "some uprooted", "ada yang tercabut akar"],
    ["。", "", "", ""],
    ["那些原在泥土中的", "nà xiē yuán zài ní tǔ zhōng de", "Those originally in the soil", "Yang asalnya dalam tanah"],
    ["树根", "shù gēn", "roots", "akar"],
    ["，", "", "", ""],
    ["裸露在", "luǒ lù zài", "exposed to", "terdedah kepada"],
    ["灰暗的天空下", "huī àn de tiān kōng xià", "the grey sky", "langit kelabu"],
    ["，", "", "", ""],
    ["被雨水冲洗得", "bèi yǔ shuǐ chōng xǐ de", "washed by the rain", "dibasuh hujan"],
    ["黄里泛白", "huáng lǐ fàn bái", "yellowish-white", "keputih-putihan"],
    ["。", "", "", ""],
    ["我们", "wǒ men", "We", "Kami"],
    ["在菜园里", "zài cài yuán lǐ", "in the garden", "di kebun"],
    ["凭吊了半天", "píng diào le bàn tiān", "mourned for a long time", "bersedih lama"],
    ["，", "", "", ""],
    ["并非全无所获", "bìng fēi quán wú suǒ huò", "not without gain", "bukan tanpa hasil"],
    ["。", "", "", ""],
    ["那可怜的", "nà kě lián de", "Those poor", "Yang malang"],
    ["木瓜树", "mù guā shù", "papaya trees", "pokok betik"],
    ["，", "", "", ""],
    ["虽是被风雨摧折了", "suī shì bèi fēng yǔ cuī shé le", "although destroyed by the storm", "walaupun musnah oleh ribut"],
    ["，", "", "", ""],
    ["却还遗留", "què hái yí liú", "still left behind", "masih meninggalkan"],
    ["我们", "wǒ men", "us", "kami"],
    ["一篓筐的", "yī lǒu kuāng de", "a basket of", "sebakul"],
    ["青木瓜", "qīng mù guā", "green papayas", "betik muda"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    ["妹妹说", "mèi mei shuō", "My sister said", "Adik berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["以后我们", "yǐ hòu wǒ men", "In the future we", "Selepas ini kita"],
    ["再也没有木瓜吃了", "zài yě méi yǒu mù guā chī le", "won't have papayas to eat anymore", "tidak akan ada betik untuk dimakan lagi"],
    ["。”", "", "", ""],
    ["父亲却说", "fù qīn què shuō", "Father said", "Ayah pula berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["不会的", "bù huì de", "It won't happen", "Tidak akan"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["很快就会再有的", "hěn kuài jiù huì zài yǒu de", "we will have them again soon", "kita akan ada lagi tidak lama"],
    ["。”", "", "", ""],
    ["那时", "nà shí", "At that time", "Pada masa itu"],
    ["我和妹妹", "wǒ hé mèi mei", "my sister and I", "saya dan adik"],
    ["都以为", "dōu yǐ wéi", "both thought", "sama-sama fikir"],
    ["，", "", "", ""],
    ["那只是", "nà zhǐ shì", "that was just", "itu hanyalah"],
    ["父亲安慰我们的话", "fù qīn ān wèi wǒ men de huà", "father's words to comfort us", "kata-kata ayah untuk menghiburkan kami"],
    ["。", "", "", ""],
    ["然而", "rán ér", "However", "Namun"],
    ["夏天还没过去", "xià tiān hái méi guò qù", "summer hadn't passed yet", "musim panas belum berlalu"],
    ["，", "", "", ""],
    ["母亲撒下的", "mǔ qīn sā xià de", "the seeds Mother had sown", "biji yang ibu tabur"],
    ["木瓜籽", "mù guā zǐ", "papaya seeds", "biji betik"],
    ["，", "", "", ""],
    ["却真的", "què zhēn de", "really did", "benar-benar"],
    ["又长出", "yòu zhǎng chū", "sprout again", "tumbuh lagi"],
    ["嫩绿的", "nèn lǜ de", "tender green", "hijau muda"],
    ["小木瓜树来了", "xiǎo mù guā shù lái le", "small papaya trees", "pokok betik kecil"],
    ["。", "", "", ""],
    ["它们", "tā men", "They", "Mereka"],
    ["又像上次一样地", "yòu xiàng shàng cì yī yàng de", "again like last time", "lagi seperti sebelumnya"],
    ["欣欣向荣", "xīn xīn xiàng róng", "flourishing", "subur"],
    ["，", "", "", ""],
    ["逐渐壮大", "zhú jiàn zhuàng dà", "gradually growing", "semakin membesar"],
    ["，", "", "", ""],
    ["生出", "shēng chū", "bearing", "menghasilkan"],
    ["累累的果实", "lěi lěi de guǒ shí", "abundant fruits", "buah yang lebat"],
    ["。", "", "", ""],
    ["我一方面", "wǒ yī fāng miàn", "On one hand I", "Di satu pihak saya"],
    ["觉得很快乐", "jué de hěn kuài lè", "felt very happy", "merasa sangat gembira"],
    ["，", "", "", ""],
    ["一方面", "yī fāng miàn", "on the other hand", "di sisi lain"],
    ["却又", "què yòu", "yet also", "tetapi juga"],
    ["有点儿忧愁", "yǒu diǎn r yōu chóu", "a bit worried", "agak bimbang"],
    ["，", "", "", ""],
    ["怕再来一次大台风", "pà zài lái yī cì dà tái fēng", "afraid of another big typhoon", "takut taufan besar lagi"],
    ["，", "", "", ""],
    ["又会", "yòu huì", "would again", "akan lagi"],
    ["把木瓜树给吹倒", "bǎ mù guā shù gěi chuī dǎo", "blow down the papaya trees", "menumbangkan pokok betik"],
    ["。", "", "", ""],
    ["我把", "wǒ bǎ", "I", "Saya"],
    ["这心里的忧愁", "zhè xīn lǐ de yōu chóu", "this worry in my heart", "kebimbangan dalam hati ini"],
    ["告诉父亲", "gào su fù qīn", "told Father", "memberitahu ayah"],
    ["，", "", "", ""],
    ["他却笑着说", "tā què xiào zhe shuō", "but he smiled and said", "tetapi dia tersenyum dan berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["没关系", "méi guān xi", "It doesn't matter", "Tak apa"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["还可以再种呀", "hái kě yǐ zài zhòng ya", "can plant again", "boleh tanam lagi"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第13段

    ["父亲还说", "fù qīn hái shuō", "Father also said", "Ayah juga berkata"],
    ["，", "", "", ""],
    ["天灾", "tiān zāi", "Natural disasters", "Bencana alam"],
    ["虽然可怕", "suī rán kě pà", "although frightening", "walaupun menakutkan"],
    ["，", "", "", ""],
    ["却是短暂的", "què shì duǎn zàn de", "are short-lived", "adalah sementara"],
    ["。", "", "", ""],
    ["而", "ér", "And", "Dan"],
    ["宇宙间的", "yǔ zhòu jiān de", "in the universe", "di alam semesta"],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["，", "", "", ""],
    ["即使", "jí shǐ", "even if", "walaupun"],
    ["遭遇了挫折", "zāo yù le cuò zhé", "encounters setbacks", "menghadapi kegagalan"],
    ["，", "", "", ""],
    ["也还会", "yě hái huì", "will still", "akan tetap"],
    ["生生不息", "shēng shēng bù xī", "endlessly renew", "terus hidup"],
    ["，", "", "", ""],
    ["绵绵不绝地", "mián mián bù jué de", "continuously", "tanpa putus"],
    ["延续下去", "yán xù xià qù", "continue", "berterusan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第14段

    ["父亲的话", "fù qīn de huà", "Father's words", "Kata-kata ayah"],
    ["，", "", "", ""],
    ["说的一点儿没错", "shuō de yī diǎn r méi cuò", "were absolutely right", "memang tepat"],
    ["。", "", "", ""],
    ["20年后的现在", "èr shí nián hòu de xiàn zài", "Now, 20 years later", "Sekarang, 20 tahun kemudian"],
    ["，", "", "", ""],
    ["我们菜园里", "wǒ men cài yuán lǐ", "in our garden", "di kebun kami"],
    ["仍然", "réng rán", "still", "masih"],
    ["种着", "zhòng zhe", "planted", "ditanam"],
    ["许多木瓜树", "xǔ duō mù guā shù", "many papaya trees", "banyak pokok betik"],
    ["，", "", "", ""],
    ["不知已是", "bù zhī yǐ shì", "I don't know which generation", "entah sudah"],
    ["第几代了", "dì jǐ dài le", "this is", "generasi ke berapa"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["季季", "jì jì", "Ji Ji", "Ji Ji"],
    ["《", "", "", ""],
    ["木瓜树", "mù guā shù", "Papaya Trees", "Pokok Betik"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
